# Generated by Django 2.0.5 on 2018-06-04 21:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writing_prompts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prompt',
            new_name='Entry',
        ),
    ]
